# Generated by Django 5.2.1 on 2025-06-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiadmin', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
